# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'https://rubygems.org'

gem 'rails', '~> 4.2.2'
gem 'actionmailer'

# as our database
gem 'mysql2'
# as requirement for activexml
gem 'nokogiri'
# for delayed tasks
gem 'delayed_job_active_record', '>= 4.0.0'
# as JSON library - the default json conflicts with activerecord (by means of vice-versa monkey patching)
gem 'yajl-ruby'
# to search the database
gem 'thinking-sphinx', '> 3.1'
# to paginate search results
gem 'kaminari'
# as abstract HTML of the bratwurst 'theme'
gem 'haml'
# to avoid tilt downgrade
gem 'tilt', '>= 1.4.1'
# to use markdown in the comment system
gem 'redcarpet'
# for nested attribute forms
gem 'cocoon'
# for activerecord lists. Used for AttribValues
gem 'acts_as_list'
# to parse a XML string into a ruby hash
gem 'xmlhash', '>=1.3.6'
# to escape HTML (FIXME: do we still use this?)
gem 'escape_utils'
# to sanitize HTML/CSS
gem 'sanitize'
# as authorization system
gem "pundit"
#
gem 'responders', '~> 2.0'
# needed for travis-ci.org, must be global for scripts
gem 'bundler'
# for threaded comments
gem 'acts_as_tree'
# js plotting (OBS monitor)
gem 'flot-rails'

group :development, :production do
  # to have the delayed job daemon
  gem 'daemons'
  # as memcache client
  gem 'dalli', require: false
  # to document ruby code
  gem 'rdoc'
  # to not rely on cron+rake
  gem 'clockwork', '>= 0.7'
  # as interface to LDAP
  gem 'ruby-ldap', require: false
end

group :production do
  # if you have an account, it can be configured by
  # placing a config/newrelic.yml
  # be aware about the non-OSS license
#  gem 'newrelic_rpm'
end

# Gems used only for assets and not required in production environments by default.
group :assets do
  # for minifying CSS
  gem 'cssmin', '>= 1.0.2'
  # for minifying JavaScript
  gem 'uglifier', '>= 1.2.2'
  # to use sass in the asset pipeline
  gem 'sass-rails', '~> 5.0.1'
  # assets for jQuery DataTables
  gem 'jquery-datatables-rails', '1.12.2', path: "vendor/gems/jquery-datatables-rails-1.12.2"
  # assets for the text editor
  gem 'codemirror-rails'
  # assets for jQuery tokeninput
  gem 'rails_tokeninput', '>= 1.6.1.rc1'
  # to create our sprite images/stylesheets
  gem 'sprite-factory', '>= 1.5.2'
  # to read and write PNG images
  gem 'chunky_png'
  # assets for jQuery and jQuery-ujs
  gem 'jquery-rails'
  # assets for jQuery-ui
  gem 'jquery-ui-rails', '>= 4.2.1' # version 5 needs henne's new webui
  # assets for the bootstrap front-end framework. Used by the bratwurst theme
  # gem 'bootstrap-sass-rails'
  # assets for font-awesome vector icons
  gem "font-awesome-rails"
end
